--- 
- name: Copy artifact.tar.gz to EC2
  copy:
    src: "files/artifact.tar.gz"
    dest: "~/"

- name: Extract zipped file
  unarchive: 
    src: "files/artifact.tar.gz"
    dest: "~/"

- name: "install npm"
  become: yes
  apt:
    # name: ['nodejs', 'npm', 'tar', 'gzip', 'python3']
    name: npm
    state: latest


- name: "install pm2"
  become: yes
  apt:
    name: pm2
    global: yes
    state: latest

- name: "stop default"
  become: yes
  command: pm2 stop default

- name: "start the app"
  become: yes
  command: pm2 start npm -- start

# --- 
# - name: Copy artifact.tar.gz to EC2
#   copy:
#     src: "files/artifact.tar.gz"
#     dest: "~/"

# - name: Extract zipped file
#   unarchive: 
#     src: "files/artifact.tar.gz"
#     dest: "~/"

# - name: start app
#   shell: |
#     sudo npm install
#     pm2 stop default
#     sudo pm2 start npm -- start

